services:
  postgres:
    container_name: access-control-api-pg
    image: postgres
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: access-control-api
      PGDATA: /data/postgres
